// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nfanexsrxtvpsvylkwgw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5mYW5leHNyeHR2cHN2eWxrd2d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxNTUwNjAsImV4cCI6MjA2MTczMTA2MH0.mgE4V2RQikEQSJLvlocNQ7swrWOOPFD9NI-d5KY66Oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);